import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Rasid branding colors
const COLORS = {
  primary: [0, 102, 178] as [number, number, number],     // Blue
  secondary: [212, 175, 55] as [number, number, number],   // Gold
  dark: [30, 41, 59] as [number, number, number],          // Dark blue
  light: [241, 245, 249] as [number, number, number],      // Light gray
  success: [16, 185, 129] as [number, number, number],     // Green
  warning: [245, 158, 11] as [number, number, number],     // Amber
  danger: [239, 68, 68] as [number, number, number],       // Red
  white: [255, 255, 255] as [number, number, number],
  text: [51, 65, 85] as [number, number, number],
};

import { LOGO_FULL_DARK } from "@/lib/rasidAssets";
const LOGO_URL = LOGO_FULL_DARK;

interface ReportData {
  title: string;
  modules: string[];
  data: Record<string, any>;
  dateFrom?: string;
  dateTo?: string;
  generatedBy?: string;
}

export async function generateProfessionalPDF(reportData: ReportData): Promise<Blob> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let y = 0;

  // Helper: Add page header
  const addHeader = () => {
    // Top bar
    doc.setFillColor(...COLORS.dark);
    doc.rect(0, 0, pageWidth, 8, "F");
    doc.setFillColor(...COLORS.secondary);
    doc.rect(0, 8, pageWidth, 2, "F");
  };

  // Helper: Add page footer
  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFillColor(...COLORS.dark);
    doc.rect(0, pageHeight - 12, pageWidth, 12, "F");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.white);
    doc.text(`${pageNum} / ${totalPages}`, pageWidth / 2, pageHeight - 5, { align: "center" });
    doc.text("RASID Platform - Confidential", margin, pageHeight - 5);
    doc.text(new Date().toLocaleDateString("ar-SA-u-nu-latn"), pageWidth - margin, pageHeight - 5, { align: "right" });
  };

  // Helper: Check page break
  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 25) {
      doc.addPage();
      addHeader();
      y = 18;
    }
  };

  // Helper: Add section title
  const addSectionTitle = (title: string) => {
    checkPageBreak(20);
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, y, pageWidth - margin * 2, 10, 2, 2, "F");
    doc.setFontSize(12);
    doc.setTextColor(...COLORS.white);
    doc.text(title, pageWidth - margin - 5, y + 7, { align: "right" });
    y += 15;
  };

  // ========== COVER PAGE ==========
  addHeader();

  // Title area
  y = 50;
  doc.setFillColor(...COLORS.light);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 80, 5, 5, "F");

  // Logo placeholder
  doc.setFillColor(...COLORS.primary);
  doc.circle(pageWidth / 2, y + 20, 15, "F");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.white);
  doc.text("R", pageWidth / 2, y + 25, { align: "center" });

  // Title
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.dark);
  doc.text(reportData.title || "RASID Report", pageWidth / 2, y + 48, { align: "center" });

  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);
  doc.text("RASID Platform - Compliance Monitoring", pageWidth / 2, y + 58, { align: "center" });

  // Date range
  if (reportData.dateFrom || reportData.dateTo) {
    doc.setFontSize(10);
    const dateText = `${reportData.dateFrom || "..."} - ${reportData.dateTo || "..."}`;
    doc.text(dateText, pageWidth / 2, y + 68, { align: "center" });
  }

  // Metadata
  y = 145;
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.text);
  const metaItems = [
    ["Report Date", new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })],
    ["Generated By", reportData.generatedBy || "System"],
    ["Modules", reportData.modules.length.toString()],
    ["Classification", "Confidential"],
  ];
  metaItems.forEach(([label, value], i) => {
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(label, pageWidth / 2 + 30, y + i * 8, { align: "right" });
    doc.setTextColor(...COLORS.dark);
    doc.text(value, pageWidth / 2 - 30, y + i * 8);
  });

  addFooter(1, 1); // Will be updated later

  // ========== DATA PAGES ==========
  const data = reportData.data;

  // Module: General Stats
  if (data.general_stats) {
    doc.addPage();
    addHeader();
    y = 18;
    addSectionTitle("General Statistics");
    
    const gs = data.general_stats;
    const statsRows = [
      ["Total Sites", String(gs.totalSites || 0)],
      ["Total Scans", String(gs.totalScans || 0)],
      ["Compliant", String(gs.compliant || 0)],
      ["Partially Compliant", String(gs.partiallyCompliant || 0)],
      ["Non-Compliant", String(gs.nonCompliant || 0)],
      ["No Policy", String(gs.noPolicy || 0)],
      ["Compliance Rate", `${gs.totalSites > 0 ? Math.round((gs.compliant / gs.totalSites) * 100) : 0}%`],
    ];

    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value"]],
      body: statsRows,
      theme: "grid",
      margin: { left: margin, right: margin },
      headStyles: { fillColor: COLORS.primary, fontSize: 10, halign: "center" },
      bodyStyles: { fontSize: 10, halign: "center" },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { halign: "left", fontStyle: "bold", cellWidth: 80 },
        1: { halign: "center" },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Module: Compliance Breakdown
  if (data.compliance_breakdown) {
    checkPageBreak(50);
    addSectionTitle("Compliance Breakdown");
    
    const cb = data.compliance_breakdown;
    if (Array.isArray(cb) && cb.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Status", "Count", "Percentage"]],
        body: cb.map((item: any) => [
          item.status || item.complianceStatus || "Unknown",
          String(item.count || 0),
          `${item.percentage || 0}%`,
        ]),
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: COLORS.primary, fontSize: 10, halign: "center" },
        bodyStyles: { fontSize: 10, halign: "center" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Module: Article 12 Clauses
  if (data.article12_clauses) {
    checkPageBreak(50);
    addSectionTitle("Article 12 Clauses Compliance");
    
    const clauses = data.article12_clauses;
    if (Array.isArray(clauses) && clauses.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Clause", "Compliant", "Total", "Rate"]],
        body: clauses.map((c: any) => [
          `Clause ${c.clause || c.clauseNumber || "?"}`,
          String(c.compliant || 0),
          String(c.total || 0),
          `${c.percentage || c.rate || 0}%`,
        ]),
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: COLORS.primary, fontSize: 10, halign: "center" },
        bodyStyles: { fontSize: 10, halign: "center" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        didParseCell: (data: any) => {
          if (data.section === "body" && data.column.index === 3) {
            const val = parseInt(data.cell.text[0]);
            if (val >= 70) data.cell.styles.textColor = COLORS.success;
            else if (val >= 40) data.cell.styles.textColor = COLORS.warning;
            else data.cell.styles.textColor = COLORS.danger;
          }
        },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Module: Sector Comparison
  if (data.sector_comparison) {
    checkPageBreak(50);
    addSectionTitle("Sector Comparison");
    
    const sectors = data.sector_comparison;
    if (Array.isArray(sectors) && sectors.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Sector", "Total Sites", "Compliant", "Compliance Rate"]],
        body: sectors.map((s: any) => [
          s.sector || s.sectorType || "Unknown",
          String(s.total || s.count || 0),
          String(s.compliant || 0),
          `${s.complianceRate || s.rate || 0}%`,
        ]),
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: COLORS.primary, fontSize: 10, halign: "center" },
        bodyStyles: { fontSize: 10, halign: "center" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Module: Category Breakdown
  if (data.category_breakdown) {
    checkPageBreak(50);
    addSectionTitle("Category Breakdown");
    
    const cats = data.category_breakdown;
    if (Array.isArray(cats) && cats.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Category", "Total", "Compliant", "Rate"]],
        body: cats.map((c: any) => [
          c.category || c.classification || "Unknown",
          String(c.total || c.count || 0),
          String(c.compliant || 0),
          `${c.complianceRate || c.rate || 0}%`,
        ]),
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: COLORS.primary, fontSize: 10, halign: "center" },
        bodyStyles: { fontSize: 10, halign: "center" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Module: Site Details
  if (data.site_details) {
    checkPageBreak(50);
    addSectionTitle("Site Details");
    
    const sites = data.site_details;
    if (Array.isArray(sites) && sites.length > 0) {
      const siteRows = sites.slice(0, 100).map((s: any) => [
        s.siteName || s.domain || "Unknown",
        s.domain || "",
        s.sectorType === "public" ? "Public" : "Private",
        s.overallScore != null ? `${Math.round(Number(s.overallScore))}%` : "N/A",
        s.complianceStatus || "Unknown",
      ]);

      autoTable(doc, {
        startY: y,
        head: [["Entity", "Domain", "Sector", "Score", "Status"]],
        body: siteRows,
        theme: "grid",
        margin: { left: margin, right: margin },
        headStyles: { fillColor: COLORS.primary, fontSize: 9, halign: "center" },
        bodyStyles: { fontSize: 8, halign: "center" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: {
          0: { halign: "left", cellWidth: 40 },
          1: { halign: "left", cellWidth: 40 },
        },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Update page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  return doc.output("blob");
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
